### ISSUE TITLE
Party pages are very long and lacking in detail

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/WhoCanIVoteFor#1200]
e.g. https://whocanivotefor.co.uk/parties/party:52/conservative-and-unionist-party lists 33,040 candidates and takes about 20 seconds to load

It's not very informative in its current state - there are no dates, and no links back to the elections, and the posts appear to be in date order, then alphabetical order of post, without any grouping by election:

![image](https://user-images.githubusercontent.com/10633357/165335814-fd54563e-9f87-4ba4-9bfe-2772230b721c.png)

**Comment by pmk01** [comment]
Yeah, they are the bit of WCIVF which has had the least amount of attention over the years.

I want to do a complete overhaul of party pages, with the fixes you mention. Maybe a filter system would be useful to, and a link to the EC register.

Might be useful to have a list of registered descriptions, too. 'This party can appear on the ballot paper under any of the following descriptions:'

**Comment by pmk01** [comment]
As a note to this, we should also think about improving https://whocanivotefor.co.uk/parties/ itself. 

We could, for instance, explain a little more about parties, and maybe provide links to eg https://www.electoralcommission.org.uk/who-we-are-and-what-we-do/party-registration-applications/view-current-applications

**Comment by Bekabyx** [comment]
We've done the first drop of this, completely reformatting the party pages to have more useful information such as party descriptions and emblems. 

There's still a [part two](https://trello.com/c/gziXi9a7/1761-wcivf-party-pages-part-ii) we'd like to do which will first involve updating the information that we scrape from the EC - these changes will allow us to mark emblems and descriptions as no longer in use as well as adding parties' alternative names. Issue being left open for now because of this :)

**Comment by pmk01** [comment]
🥳
