### ISSUE TITLE
wikipedia isn't updating

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#1625]
![Screenshot 2023-06-19 111007](https://github.com/DemocracyClub/WhoCanIVoteFor/assets/61510609/2b637013-cf37-4211-8226-383f2b0ce263)

**Comment by VirginiaDooley** [comment]
Update: After not running for several months due to a failed rollback, I've confirmed this job has run on 5/9/23. However, the job is designed to only run imports for current candidates, which would not include the individual above. I think if we remove the `--current` flag from the job then all candidates - current and past - will receive up to date wikipedia bios. Before I raise this PR, is there any other limitation we want to place on wikipedia imports? Or any unforeseen consequence of removing the flag? @symroe
