### ISSUE TITLE
Use upstream proxy to cache pages

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#177]
Consider sticking [CloudFlare](https://www.cloudflare.com) in front of everything? It's not expensive, and it makes life a lot less stressful when you're expecting high traffic. 

To deal with daily page updates, we can just flush the cache via the CloudFlare API after the cron jobs, and then optionally re-warm it using a script to walk over the URls in the sitemap. 

I use CloudFlare very happily on all my projects.

**Comment by symroe** [comment]
The problem with this is that we have a long tail of URLs that we expect to get hit. We could warm the cache, but with 1.8 million postcodes it would take ages and be hard to clear. 

We already cache the results in Redis, and the home page doesn't hit the database at all.

The other option that @boffbowsh raised was to key the results off constituency. This would results in 650 pages to cache, making a CDN really worthwhile.

There are two problems with this: 

1. It doesn't account for >1 election in an area (this isn't much of a problem this time around, but it will be in future)

2. We need a postcode for the polling station finder block to work (and the feedback). This means that each page would need to be passed a postcode somehow, breaking cache per constituency anyway.

Also, the way the deployment is done means that there are no central bottle necks. Each instance has the ability to do postcode -> elections look up locally and contains the candidates database.

This means that, in theory, the load should scale equally to the number of servers, as long as the ELB can scale as quickly as we want it to.

Having said that, there are a couple of points of failure:

1. The candidate images are hot linking to `candidates.democracyclub.org.uk`. This is a fairly powerful server and serving static images isn't hard, but we might want to move these to S3 anyway, just in case.

2. The Redis caches are currently on each instance, not in a single place. This means that a new server wont be cache warmed at all, and the existing servers will only cache the requests it gets sent, not all requests.

3. The home page can be behind a CDN, because as @boffbowsh says, not getting hit at all is best of all.

I might look at putting CloudFront in front of the site, as that's going to be a bit quicker to set up than a non-AWS thing.

**Comment by annapowellsmith** [comment]
You could cache just the candidate pages and post (i.e. constituency) pages, not the postcode pages?

That would help with the traffic from people arriving directly on candidate and constituency pages via Google. 

I don't have GA access so can't check, but I'd guess that's a good percentage of all the traffic, particularly over the next 10 days (think @davidmiller said there was a long tail of traffic from Google searches). 

You can then keep the postcode lookup exactly as it is, and with the overall load reduced.

I have no particular view on which solution is best, but would observe that CloudFlare is super easy to set up, it's just DNS.

**Comment by chris48s** [comment]
> The candidate images are hot linking to `candidates.democracyclub.org.uk`

Also the leaflet images are directly linked off `electionleaflets.org`
