### ISSUE TITLE
Confusing wording for Mayoral Elections

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#265]
e.g: https://whocanivotefor.co.uk/elections/N16%206UP/

Nothing makes it clear this is a mayoral election, inappropriate use of the word 'ward'

![screenshot at 2018-04-23 09 42 59](https://user-images.githubusercontent.com/6025893/39116044-4c1bcf8a-46db-11e8-8c59-a8d1b899c757.png)

**Comment by JoeMitchell** [comment]
You beat me to it! But I reckon this is a high-priority thing to work on. It looks bad. 

Related, but less important: #236

**Comment by symroe** [comment]
I think this is actually because WCIVF is taking the election name from EE (via YNR, that also has the same name). In EE the [election title is "London Borough of Hackney"](https://elections.democracyclub.org.uk/api/elections/mayor.hackney.2018-05-03/).

I can write some code to make it nicer on WCIVF, but I think longer term the solution is to have titles that can be used in different contexts in EE, and propagate them down to consumers of the data.

**Comment by chris48s** [comment]
Yep, so moving forwards there is a bit of work to do on the `to_title()` method here:

https://github.com/DemocracyClub/EveryElection/blob/67d3c241dafd5a9975b4c61f0aede4392dc278db/every_election/apps/elections/utils.py#L138-L156

so that new elections we create of this type have a more pleasing title (probs using the `elected_role` in the title). This is run when we create an election. In terms of improving this for the 6 mayoral elections happening next week which we've already created, what's the best approach? Change them manually in EE (via `/admin`) so they sync through to YNR and then WhoCIVF?

Referring to the whole organisation as a 'ward' is a fix that does need to be applied here though, I think.

**Comment by chris48s** [comment]
Raised as https://github.com/DemocracyClub/EveryElection/issues/264

**Comment by symroe** [comment]
Just pushed a manual fix in this codebase for the election names, and at the same time a manual fix for the 'ward' problem – this isn't really a solution, but it makes things nicer over the next week (the only time that it matters)

**Comment by symroe** [comment]
Deploy, and looks like this: ![screenshot 2018-04-23 13 25 19](https://user-images.githubusercontent.com/242329/39126266-cb9d5bca-46f9-11e8-80cb-fa536e35256f.png)

**Comment by jf1** [comment]
I believe all names and phrases could be fixed with a structured system driven by a single table. I did the below >6 months ago so would need to revisit it to get familiar with all its details. The comment on the sub-division header is: "If no sub-division then the election area is the entire Organisation area"

![image](https://user-images.githubusercontent.com/4711363/39125912-8990be6c-46f8-11e8-86d9-3527ca407e26.png)

Basically each ??? (do you call these an 'election type'?) would need to be complimented with 3 extra text labels (T1, T2, T3), a sub-type (area, list, mayor, pcc) and a flag (based greyness in Orgs) to specify if there's one election per body of if it's a 'sub-election' (ie lists or mayor to compliment constituencies being covered by the same election).

Manual (temporary?) workarounds may make things less bad during an election, but imho issues like this continue to confuse users and crowdsourcers alike, and if they leave dissatisfied there's every chance it'd be harder to get them back than if they'd never visited.

Does this issue need to be closed, and if so please can you start a new one for the more fundamental, long-term fix?

**Comment by JoeMitchell** [comment]
Ah, the EC have the same problem — should we let them know? https://www.yourvotematters.co.uk/postcode-results?query=n16+6up

**Comment by symroe** [comment]
Sorted it by doing the same as above. Let's not risk breaking anything right now and look at it later.

![screen shot 2018-04-23 at 16 54 47](https://user-images.githubusercontent.com/242329/39138149-37a47b2e-4717-11e8-901c-cb358a47ee15.png)

**Comment by JoeMitchell** [comment]
They never even saw it happen. :D
