### ISSUE TITLE
Questions from Porism

### ISSUE THREAD

**Issue by MikeThacker1** [DemocracyClub/WhoCanIVoteFor#29]
We have four questions if you don't mind. Tell me if I should put these elsewhere or split them up:

1. Is there a source of current councillors? Can we identify which cease to be valid after 5 May unless re-elected?  Can we identify ones that have stood down since election?
2. When will the results API be available and what is format of calls?  How do we test?
3. When will the result RSS be available and what is format of calls?  How do we test?  Can we have different feeds or a filter for validated or not?  Can we have a filter for "updated since date/time"?
4. How do we provide results on the night?  I've registered with OutForTheCount.  Do I just wait to be contacted?

Thanks
Mike

**Comment by andylolz** [comment]
Hi Mike,

Question 1: I don’t think we have a source for current councillors, though it’s an interesting question. Rather than keeping an ongoing record of current politicians in office, WhoCanIVoteFor / YourNextRepresentative both attempt to provide a snapshot of the ballots for a given election. As such, there is no way to record politicians standing down, or even which candidates are currently serving as politicians.

I suspect questions 2 & 3 are probably better created as an issue on: https://github.com/DemocracyClub/ResultsRecorder
I don’t have an answer I’m afraid, but I’m sure somewhere there will be able to help.

Question 4: Another good question! I suspect @JoeMitchell can provide a contact address for this one?

Hope that’s of some help.

**Comment by MikeThacker1** [comment]
Thanks @andylolz. I've created an issue in https://github.com/DemocracyClub/ResultsRecorder.

If anyone knows of a source of current councillors elsewhere, do chip in.  Otherwise, we might be able to collect/scrape these over time and make them available as open data.

**Comment by andylolz** [comment]
> 4) How do we provide results on the night? I've registered with OutForTheCount. Do I just wait to be contacted?

I just signed up, and received an email from LGiU shortly after.

**Comment by JoeMitchell** [comment]
Yeah, there's definitely demand for this list from campaign groups (there's
an email on ECF today about council leaders).

mySoc get the one for WriteToThem from a little provider listed on their
website somewhere.

@Mike, it'll be in the spanking new results recorder - details will follow!
Did you get any kind of confirmation email? I can chat to LGiU about
putting one in if you didn't....(I can't remember what happened when I
signed up)

**Comment by andylolz** [comment]
> mySoc get the one for WriteToThem from a little provider listed on their
> website somewhere.

Ah yes! @JoeMitchell is absolutely right. They’re called GovEval:
https://www.writetothem.com/about-copyright

**Comment by MikeThacker1** [comment]
Yes I got a confirmation message when I registered.  Looking forward to the results recorder.  Thanks
