### ISSUE TITLE
Always set future elections as current

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/WhoCanIVoteFor#499]
Future (not current) elections are referred to in the past tense, e.g. https://whocanivotefor.co.uk/person/1478/shaun-bailey

![image](https://user-images.githubusercontent.com/10633357/68997736-7c83f100-08a1-11ea-827f-4908aad8478d.png)

![image](https://user-images.githubusercontent.com/10633357/68997741-83aaff00-08a1-11ea-99c1-7c8bda829932.png)

**Comment by chris48s** [comment]
I suspect this is probably a place where we're using `current` instead of `future`. I probably accidentally introduced this in https://github.com/DemocracyClub/WhoCanIVoteFor/pull/462

**Comment by symroe** [comment]
The solution here is to set elections in the future as `current` at import time. We _should_ set this upstream, but if we're going to show them on this site, we should show them correctly.

An alternative would be to hide elections in the future that aren't marked as current. I can't see why this would be useful - if we have an election in EE then it's generally going to be useful to show that to the public. 

If we decide to hide `future and not current` then we also need to do this on WDIV, otherwise devs.DC blows up due to mismatched ballot lists.
