### ISSUE TITLE
Limit bio information for non-current candidates

### ISSUE THREAD

**Issue by michaeljcollinsuk** [DemocracyClub/WhoCanIVoteFor#626]
Linked to https://trello.com/c/d1aYISge/87-wcivf-stop-showing-bio-info-for-non-current-candidates

Display a stripped down set of information for a candidate if they do not have a current or future candidacy. For example:

Intro:
'Name' was the 'Party' candidate in 'District' in the 'Election.

Previous elections

**Comment by symroe** [comment]
Implementation note:

This information is imported with the `import_ballots` command (it adds candidacies only). `import_people` imports all the other biographical data.

Because of this, we could have a command that removes data from people who don't have a candidacy on a current or future ballot.

Defining the list of fields to remove is the tricky bit - can we find a way to generate the list of extra info and allow-list the fields we want to keep? Maybe using `Person._meta.fields`?

**Comment by michaeljcollinsuk** [comment]
If no current candidacies we should add a no-index tag to the page
