### ISSUE TITLE
Enhance How you vote information for all elections

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/WhoCanIVoteFor#719]
### Issue and Steps to Reproduce
https://whocanivotefor.co.uk/elections/local.monmouthshire.st-kingsmark.by.2021-04-01/st-kingsmark/ 
How you vote is currently only enabled for by-elections in (country) when the ballot is locked

### Screenshots

<img width="494" alt="Screen Shot 2021-03-30 at 10 39 15 AM" src="https://user-images.githubusercontent.com/7017118/112968517-48cb0380-9144-11eb-872d-4ac2943ed69c.png">

#### Expected

- [x] Enable How you vote for all elections
- [x] Add link for first past the post
- [x] Customise how to for each election - @pmk01 will advise

**Comment by pmk01** [comment]
There are **three** electoral systems in use on 6 May. We want to modify all of them to some extent.

**First Past the Post** 
In the text 'This election uses First-Past-the-Post', I'd like 'First-past-the-pose' to link to a page on WCIVF [containing this text.](https://docs.google.com/document/d/1njJxHolV3_kp4nnjWltWdyZP1i1zs9FB0H3Sz2WIDMs/edit)

If number of seats = greater than one, we should display the text "Mark an X in the box for your preferred candidates. You can vote for up to [n] candidates in this election".

**Supplementary Vote:**
In the text 'This election uses Supplementary Vote', I'd like 'Supplementary Vote' to link to a page on WCIVF [containing this text.](https://docs.google.com/document/d/1Pqm_xncbSYC-Dl3L0pD43qMmcFO_4UTN9SarlLnmA-8/edit)

I am otherwise happy with the SV text.

**Additional Member System:** This is the most complex and at the moment we don't have any text for it. In the text 'This election uses Additional Member System', I'd like 'Additional Member System' to link to a page on WCIVF [containing this text.](https://docs.google.com/document/d/1luzhcifh1TjNyYeim9PtSlWuxfbskLta7MunHLOT5A4/edit)

After that header, I think we should split it up to show different text for each ballot.

Constituency seats (sp.c, senedd.c, gla.c): 'Mark an X in the box for your preferred candidate.'

Regional seats (sp.r, senedd.r, gla.a): 'Mark an X in the box next to your preferred party or independent candidate.'


Hope this is all clear, it may not be!

**Comment by VirginiaDooley** [comment]
@pmk01 is it important for each explainer text to be located on separate pages or can it go on one page with anchors?

**Comment by VirginiaDooley** [comment]
@pmk01 Re: FPTP changes 
This feels confusing to me so wanted to double check wording: 
![Screen Shot 2021-04-08 at 5 47 44 PM](https://user-images.githubusercontent.com/7017118/114065510-a4a73200-9892-11eb-858b-542f1015e75e.png)

**Comment by pmk01** [comment]
yep!
