### ISSUE TITLE
People by party lists are not alphabetised

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/WhoCanIVoteFor#786]
https://whocanivotefor.co.uk/elections/W8%204NU/
![Screen Shot 2021-04-29 at 12 08 02 PM](https://user-images.githubusercontent.com/7017118/116541786-cf116b80-a8e3-11eb-959c-50e755a3bf3b.png)

**Comment by symroe** [comment]
Ah, I think this one is by design:

https://github.com/DemocracyClub/WhoCanIVoteFor/blob/e1d0541dfc9f085ffcf4058e9d741649b1d20efe/wcivf/apps/elections/views/mixins.py#L103

These candidates are sorted by their list position. Having seen this, I think we should include "list position: `n`" on these cards to make this clear!

**Comment by VirginiaDooley** [comment]
Fixed in https://github.com/DemocracyClub/WhoCanIVoteFor/pull/792
