### ISSUE TITLE
Add text when a ballot is uncontested

### ISSUE THREAD

**Issue by michaeljcollinsuk** [DemocracyClub/WhoCanIVoteFor#931]
### Issue and Steps to Reproduce
If a ballot is uncontested, on the ballot page ([example of uncontested ballot here](https://whocanivotefor.co.uk/elections/local.ceredigion.llandyfriog.2017-06-08/llandyfriog/)) we should add text to make this clear. Suggested text from @pmk01 :

> Uncontested Election
>
> This election was uncontested because only one candidate came forward to stand for each available seat.
>
>No votes will be cast, and the candidate/s below has/have been automatically declared the winner/s.

Then on the person page, we should update the results table to say "Elected unopposed" instead of "Vote count not available (elected)" ([example here](https://whocanivotefor.co.uk/person/26670/james-wyn-reynolds-thomas))

**Comment by sjorford** [comment]
It is possible for there to be fewer candidates than seats e.g. [local.north-kesteven.billinghay-martin-and-north-kyme.2019-05-02](https://candidates.democracyclub.org.uk/elections/local.north-kesteven.billinghay-martin-and-north-kyme.2019-05-02/) where only one candidate ran for a two-seat ward. So the wording could read:

>Uncontested Election
>This election was uncontested because the number of candidates was less than or equal to the number of seats.
>No votes will be cast, and the candidate/s below has/have been automatically declared the winner/s.

**Comment by chris48s** [comment]
In the case where one candidate stands for a two seat ward, presumably there is some extra complexity there because the candidate who stood gets one of the seats but then there's an immediate vacancy (and hence by-election) for the other seat - right? So I guess in the example there https://candidates.democracyclub.org.uk/elections/local.north-kesteven.billinghay-martin-and-north-kyme.by.2019-06-13/ is the corresponding by-election for the second vacancy

**Comment by sjorford** [comment]
Yes, that's right - the by-election has to be held within 35 working days of the original election date ([RoPA 1983 39(1)](https://www.legislation.gov.uk/ukpga/1983/2/section/39))

**Comment by pmk01** [comment]
Hmm, thanks for pointing this out. I think we'd want separate text to cover these eventualities (I'm concerned that "less than or equal to" would create unnecessary confusion). I also think we'd want to tell people that the election will be rescheduled.

Perhaps:

**In the case of fewer candidates than seats but where number of candidates is [more than one](https://candidates.democracyclub.org.uk/elections/local.north-kesteven.billinghay-martin-and-north-kyme.2019-05-02/): **

Uncontested and Rescheduled Election
This election was uncontested because the number of candidates who was less than the number of available seats.
There are X seats in this ward/division, and only Y candidates.

No votes will be cast, and the candidate/s below has/have been automatically declared the winner/s. A new election to fill the unclaimed seat/s will be held within 35 days of the original election date.

**In the case where [no-one turns up at all:](https://candidates.democracyclub.org.uk/elections/local.isles-of-scilly.bryher.2021-05-06/sopn/)**

Rescheduled election
This election will not take place because no candidates have been nominated to stand. [<maybe this could be a link to the SoPN?]

A new election to fill the unclaimed seat/s will be held within 35 days of the original election date.


Thoughts? @michaeljcollinsuk I hope this isn't confusing things too much!

**Comment by VirginiaDooley** [comment]
> In the case where no-one turns up at all:
> 
> Rescheduled election
> This election will not take place because no candidates have been nominated to stand. [<maybe this could be a link to the SoPN?]
> 
> A new election to fill the unclaimed seat/s will be held within 35 working days of the original election date.
> 

@pmk01 Is this^^ bit in place of the [current text](https://whocanivotefor.co.uk/elections/local.isles-of-scilly.bryher.2021-05-06/) or should it be combined?
