### ISSUE TITLE
Provide info on where a candidate ranked in previous elections

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#942]
Where we hold vote counts, it would be nice to show users how a candidate did, to give some context to the raw number.

![Screenshot 2021-11-03 100826](https://user-images.githubusercontent.com/61510609/140042004-0799bb3f-48b8-4d10-84a4-4f2d45235b84.png)

**Comment by symroe** [comment]
Hi @danielgriffin48!

Thanks for the offer!

Before diving in to your questions:

This project actually takes all its data from https://github.com/DemocracyClub/yournextrepresentative / https://candidates.democracyclub.org.uk/. 

The general pattern is that we manage all the data there, and then import a "read only" version of that data into this project. This is partly to keep this project simple, and all the business logic in one place.

So, I think it's a better idea to start there. We have a model in YNR (as we call it) that stores the results, and also deals with tie breakers:

https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/uk_results/models.py#L112

Adding a "winning_position" or "rank" field to that model and calculating at the point of data entry seems like the best method. The data is processes in this form: https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/uk_results/forms.py#L122

Next, we'll want to expose the data in the YNR API, and then update this project to consume the data, store it, and display it on the site. You should be able to get an idea of the shape of the PR needed for this project here: https://github.com/DemocracyClub/WhoCanIVoteFor/pull/1120/commits

As for your questions, I think @pmk01 might have some input, but my take is:

1. Yes, I think this is how it works
2. Again, that seems to make sense. There's no tie break for non-elected candidates as far as I know, so we'd have to mark them as joint `n`th, and the next person as `n`th+1
3. Yes this is correct. This is especially important when there have been new boundary change. This is because, if the ward elects in thirds normally, all members will be elected after a boundary change, but the one with the fewest votes has the shortest term, the second fewest has the second shortest, etc. So there is a concept of "third place winner" in the way elections are administered.

**Comment by pmk01** [comment]
Hi Daniel - I agree with all of the above. Apologies for my somewhat rough design work 😅. 

Thanks so much for offering to help, it's enormously appreciated! If you want to keep in closer contact with Democracy Club I suggest joining our [Slack group](https://slack.democracyclub.org.uk/).
